app/urls.py
from django.urls import path

from .views import *

app_name = 'app'

urlpatterns = [

    path('home/', home, name = 'home'),

]

htmx_urlpatterns = [

    path('create-folder/', create_folder, name = 'create-folder'),
    path('get-folder/<uuid:uid>/', get_folder, name = 'get-folder'),
    path('edit-folder/<uuid:uid>/', edit_folder, name = 'edit-folder'),
    path('delete-folder/<uuid:uid>/', delete_folder, name = 'delete-folder'),

    path('create-note/', create_note, name = 'create-note'),
    path('get-note/<uuid:uid>/', get_note, name = 'get-note'),
    path('pin-note/<uuid:uid>/', pin_note, name = 'pin-note'),
    path('acrhive-note/<uuid:uid>/', archive_note, name = 'acrhive-note'),
    path('delete-note/<uuid:uid>/', delete_note, name = 'delete-note'),
    path('add-image/<uuid:uid>/', add_image, name = 'add-image')

]

ajax_urlpatterns = [

    path('edit-note/<uuid:uid>/', edit_note, name = 'edit-note'),
    path('love-note/', love_note, name = 'love-note'),
    path('change-note-color', change_note_color, name = 'change-note-color'),

]

urlpatterns += htmx_urlpatterns
urlpatterns += ajax_urlpatterns

bloknotik/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('base.urls')),
    path('', include('user.urls')),
    path('', include('app.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/templates/components/folder-list.html
{% for folder in folders %}

    <div class="page">

        <span>

            {{ folder.title }}

        </span>

        <div class="edit-notepad-btn">

            E

        </div>

    </div>

{% endfor %}


<div class="folder-form">

    <div class="folder-form-wrapper">

        <div class="close-folder-form-btn">

            X

        </div>

        <span class="section-title">

            Новый блокнот

        </span>

        <form>`

            {% csrf_token %}

            <input type="text" name="title">

            <button class='create-folder-btn' hx-post="{% url 'app:create-folder' %}" hx-target=".folders">

                Создать

            </button>

        </form>

    </div>

</div>

app/templates/components/folders.html
{% for folder in folders %}

    <div class="page" 
    hx-get="{% url 'app:get-folder' folder.uid %}"
    hx-target=".notes">

        <span>

            {{ folder.title }}

        </span>

        <div class="edit-notepad-btn">

            E

        </div>

    </div>

{% endfor %}


<div class="folder-form">

    <div class="folder-form-wrapper">

        <div class="close-folder-form-btn">

            X

        </div>

        <span class="section-title">

            Новый блокнот

        </span>

        <form>`

            {% csrf_token %}

            <input type="text" name="title">

            <button class='create-folder-btn' hx-post="{% url 'app:create-folder' %}" hx-target=".folders">

                Создать

            </button>

        </form>

    </div>

</div>

app/templates/components/new-note-images.html
{% for image in images %}

    <img src="{{ image.file.url }}">

{% endfor %}

app/templates/components/note-images.html
{% for image in note.images.all %}

    <img src="{{ image.file.url }}">

{% endfor %}

app/templates/components/note.html
{{ edited_at }}

app/templates/components/notes.html
{% for note in notes %}

    <div class='note' id="{{ note.uid }}" hx-trigger="click target:.note," hx-get="{% url 'app:get-note' note.uid %} " hx-target=".current-note" style="background-color: {{ note.color }}">

        <div class="contents">

            <div class="images">

                {% include 'components/note-images.html' %}

            </div>

            <span class="title" hx-get="{% url 'app:get-note' note.uid %} " hx-target=".current-note">

                {{ note.title }}
    
            </span>

            <span class="content" hx-get="{% url 'app:get-note' note.uid %} " hx-target=".current-note">

                {{ note.content | safe }}

            </span>

        </div>

        <div class="actions">

            <div id="change-note-color-btn" onClick="changeColorInit(this)">

                C

            </div>

            <div id="add-image" onClick="addImage()">

                I

                <form hx-encoding="multipart/form-data"
                    hx-post="{% url 'app:add-image' note.uid %}"
                    hx-target=".images"
                >
                    {% csrf_token %}

                    <input type="file" name="file" id="image-file" hidden/>

                    <button type="submit" hidden></button>

                </form>

            </div>

            <div class="delete" hx-post="{% url 'app:delete-note' note.uid %}" hx-target='.notes'>
    
                D
    
            </div>
    
        </div>

    </div>

    

{% endfor %}

<script>


    /* Note labels */

    /* Note images */

 
/* 
    $('#image-file').change(function() {

        $(this).siblings('button').click();

    }) */

    /* Note background */

    let changeColorHTML = `

        <div class="note-style">

            <div class="colors">

                <div class="color" id="red" onClick="changeColor(this)" style="background-color: red;"></div>

            </div>


            <div class="wallpapers">

                <div class="wallpaper"></div>

            </div>

        </div>

    `

    var changeColorOpen = false;
    var note;

    function changeColorInit(e) {

        note = e.parentNode.parentNode;

        if (!$('.change-note-background-form').length) {

            note.insertAdjacentHTML('afterend', changeColorHTML);

        }

        changeColorOpen = true;    
        
        $('body').click(function(e) {

        if ($('.change-note-background-form').length) {

            if (!($(e.target).is($('.change-note-background-form'))) && !($(e.target).is($('.colors'))) && !($(e.target).is($('.color'))) && !($(e.target).is($('#change-note-color-btn')))) {

                $('.change-note-background-form').remove();

                changeColorOpen = false;
                
            }

        }

    }) 
        if ($('.change-note-background-form').length) {

            if (!($(e.target).is($('.change-note-background-form'))) && !($(e.target).is($('.colors'))) && !($(e.target).is($('.color'))) && !($(e.target).is($('#change-note-color-btn')))) {

                $('.change-note-background-form').remove();

                changeColorOpen = false;
                
            }

        }

    }) 
        


    function changeColor(e) {

        note.style.background = e.id;

        $.ajax({

            type: "POST",
            url: "{% url 'app:change-note-color' %}",
            data: {

                'csrfmiddlewaretoken': "{{ csrf_token }}",
                'uid': note.id,
                'color': e.id,
                

            },

        })

    }

</script>