app/urls.py
from django.urls import path

from .views import *

app_name = 'app'

urlpatterns = [

    path('home/', home, name = 'home'),

]

htmx_urlpatterns = [

    path('create-folder/', create_folder, name = 'create-folder'),
    path('get-folder/<uuid:uid>/', get_folder, name = 'get-folder'),
    path('edit-folder/<uuid:uid>/', edit_folder, name = 'edit-folder'),
    path('delete-folder/<uuid:uid>/', delete_folder, name = 'delete-folder'),

    path('create-note/', create_note, name = 'create-note'),
    path('get-note/<uuid:uid>/', get_note, name = 'get-note'),
    path('pin-note/<uuid:uid>/', pin_note, name = 'pin-note'),
    path('acrhive-note/<uuid:uid>/', archive_note, name = 'acrhive-note'),
    path('delete-note/<uuid:uid>/', delete_note, name = 'delete-note'),
    path('add-image/<uuid:uid>/', add_image, name = 'add-image')

]

ajax_urlpatterns = [

    path('edit-note/<uuid:uid>/', edit_note, name = 'edit-note'),
    path('love-note/', love_note, name = 'love-note'),
    path('change-note-color', change_note_color, name = 'change-note-color'),

]

urlpatterns += htmx_urlpatterns
urlpatterns += ajax_urlpatterns

base/urls.py
from django.urls import path

from .views import *

app_name = 'base'

urlpatterns = [

    path('', landing, name = 'landing'),

    path('plans/', plans, name = 'plans'),

    path('contact-us/', contact, name = 'contact'),

    # Info
    path('terms/', terms, name = 'terms'),
    path('privacy/', privacy, name = 'privacy'),
    path('juridical-information/', juridical, name = 'juridical'),
    path('online-payment-safety/', online_payment_safety, name = 'online-payment-safety'),
    path('data-safety/', data_safety, name = 'data-safety'),

]

bloknotik/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('base.urls')),
    path('', include('user.urls')),
    path('', include('app.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from django.conf import settings

from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'user'

urlpatterns = [

    path('login/', log_in, name = 'login'),
    path('register/', register, name = 'register'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name = 'logout'),

]

base/models.py
from django.db import models as m

from django.contrib.auth.models import User

from tinymce.models import HTMLField

class Info(m.Model):

    title = m.CharField(max_length = 300)

    content = HTMLField() 

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        return self.title

    class Meta:

        ordering = ['-title']


class FutureFeature(m.Model):

    title = m.TextField()
    description = m.TextField()

    internal = m.BooleanField(default = False)

    completed = m.BooleanField(default = False)
    completion_date = m.DateField(blank = True)

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        return self.title

    class Meta:

        ordering = ['title']

class UserFeedback(m.Model):

    user = m.OneToOneField(User, on_delete = m.CASCADE, null = True, related_name = 'user_feedback')
    anonymous = m.BooleanField(default = True)

    name = m.TextField(blank = True)

    feedback = m.TextField(blank = True)
    rating = m.PositiveSmallIntegerField(default = 5)

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        if self.user:

            return self.user.username

    class Meta:

        ordering = ['-updated_at']

base/views.py
from django.shortcuts import render

from .models import Info

def landing(request):

    c = {}

    c['logged_in'] = request.user.is_authenticated

    print(c['logged_in'])

    return render(request, 'landing.html', c)

def contact(request):

    return render(request, 'contact.html')

def plans(request):

    return render(request, 'plans.html')

# Info
def terms(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Договор-оферта'), 'id': 'agreement'})

def privacy(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Политика конфиденциальности'), 'id': 'privacy'})

def juridical(request):

    return render(request, 'info/juridical.html')

def online_payment_safety(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Безопасность онлайн платежей'), 'id': 'payment-safety'})
    
def data_safety(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Безопасность данных'), 'id': 'data-safety'})

base/templates/navs/bottom-nav.html
<div class="contents">

    <h1>

        © <i><span class="name">Блокнотик</span> 2022</i>                         

    </h1>

    <ul>

        <li>

            <a href="{% url 'base:terms' %}" target="_blank">

                Информация

            </a>

        </li>

    
        <li>

            <a href="{% url 'base:plans' %}" target="_blank">

                Тарифы

            </a>

        </li>

        <li>

            <a href="{% url 'base:contact' %}" target="_blank">

                Обратная связь

            </a>

        </li>

        <li>

            <a href="{% url 'pay:donate' %}" target="_blank">

                Помочь Блокнотику

            </a>

        </li>

        

    </ul>

</div>

<script>


    /* Brand name animation */
    setInterval( function () {

        $('.name').css({

            color: randomColor(),

        }) 

    }, 2500)

</script>

base/templates/navs/top-nav.html
<div class='left'>


    <div>

        <svg xmlns="http://www.w3.org/2000/svg" width="19.394" height="28.21" viewBox="0 0 19.394 28.21">
            <path id="Icon_awesome-lightbulb" data-name="Icon awesome-lightbulb" d="M5.293,25.033a1.764,1.764,0,0,0,.3.975l.942,1.415A1.763,1.763,0,0,0,8,28.21h3.4a1.763,1.763,0,0,0,1.468-.787l.942-1.415a1.762,1.762,0,0,0,.3-.975l0-2.113H5.29l0,2.113ZM0,9.7a9.643,9.643,0,0,0,2.4,6.379,15.834,15.834,0,0,1,2.877,5.039c0,.014.006.043.006.043h8.829c0-.014,0-.028.006-.043a15.834,15.834,0,0,1,2.877-5.039A9.7,9.7,0,1,0,0,9.7ZM9.7,5.289A4.413,4.413,0,0,0,5.289,9.7a.882.882,0,0,1-1.763,0A6.178,6.178,0,0,1,9.7,3.526a.882.882,0,0,1,0,1.763Z" transform="translate(0 0)"/>
        </svg>          

    </div>


</div>


<div class='right'>
    
    <div>

        {% if logged_in %}

                <a href="{% url 'app:home' %}">

                    <div>
                        
                        <svg xmlns="http://www.w3.org/2000/svg" width="29.174" height="25.726" viewBox="0 0 29.174 25.726">
                            <path id="Icon_material-home" data-name="Icon material-home" d="M14.192,28.373c1.755-2.106-1.4-6.319,0-8.426a3.286,3.286,0,0,1,5.617,0c1.4,2.106-1.755,6.319,0,8.426s5.266,2.809,7.022,0,0-11.234,0-11.234,6.67,3.16,4.213,0S24.023,4.5,17,4.5,5.416,13.979,2.958,17.139s4.213,0,4.213,0-1.755,8.426,0,11.234S12.437,30.48,14.192,28.373Z" transform="translate(-2.414 -4.5)"/>
                        </svg>  
            
                    </div>
            
                </a>
            
                <a href="{% url 'user:logout' %}">
            
                    <div>
            
                        <svg xmlns="http://www.w3.org/2000/svg" width="28.618" height="27.77" viewBox="0 0 28.618 27.77">
                            <path id="Icon_open-account-logout" data-name="Icon open-account-logout" d="M9.606-1.086c-4,.8-3.2,2.4,0,3.2s9.606-4,12.808,0,3.2,12.007,0,16.01-9.606-.8-12.808,0-4,2.4,0,3.2,12.007,5.6,16.01,0,4-16.81,0-22.414S13.608-1.886,9.606-1.086Zm-3.2,6.4c-1.6.4-6.4,2.4-6.4,4.8s4.8,4.4,6.4,4.8,0-3.2,0-3.2,9.606.8,12.808,0,3.2-2.4,0-3.2S6.4,8.52,6.4,8.52,8,4.918,6.4,5.318Z" transform="translate(0 3.764)"/>
                          </svg>
                          
            
                    </div>
            
                </a>

            </div>

        </div>


        {% else %}

            <a href="{% url 'user:login' %}">

                <div>

                    <svg xmlns="http://www.w3.org/2000/svg" width="29.684" height="26.574" viewBox="0 0 29.684 26.574">
                        <path id="Icon_open-account-login" data-name="Icon open-account-login" d="M8.115-.324c-3.83.766-3.064,2.3,0,3.064s9.192-3.83,12.256,0,3.064,11.49,0,15.321-9.192-.766-12.256,0-3.83,2.3,0,3.064,11.49,5.362,15.321,0,3.83-16.087,0-21.449S11.946-1.09,8.115-.324ZM11.18,5.8c-1.532-.383,0,3.064,0,3.064s-9.192-.766-12.256,0-3.064,2.3,0,3.064,12.256,0,12.256,0-1.532,3.447,0,3.064,8.1-2.193,8.1-4.491S12.712,6.187,11.18,5.8Z" transform="translate(3.375 2.887)"/>
                      </svg>
                                          

                </div>

            </a>

        {% endif %}

    </div>

</div>