app/urls.py
from django.urls import path

from .views import *

app_name = 'app'

urlpatterns = [

    path('home/', home, name = 'home'),

]

htmx_urlpatterns = [

    path('create-folder/', create_folder, name = 'create-folder'),
    path('get-folder/<uuid:uid>/', get_folder, name = 'get-folder'),
    path('edit-folder/<uuid:uid>/', edit_folder, name = 'edit-folder'),
    path('delete-folder/<uuid:uid>/', delete_folder, name = 'delete-folder'),

    path('create-note/', create_note, name = 'create-note'),
    path('get-note/<uuid:uid>/', get_note, name = 'get-note'),
    path('pin-note/<uuid:uid>/', pin_note, name = 'pin-note'),
    path('acrhive-note/<uuid:uid>/', archive_note, name = 'acrhive-note'),
    path('delete-note/<uuid:uid>/', delete_note, name = 'delete-note'),
    path('add-image/<uuid:uid>/', add_image, name = 'add-image')

]

ajax_urlpatterns = [

    path('edit-note/<uuid:uid>/', edit_note, name = 'edit-note'),
    path('love-note/', love_note, name = 'love-note'),
    path('change-note-color', change_note_color, name = 'change-note-color'),

]

urlpatterns += htmx_urlpatterns
urlpatterns += ajax_urlpatterns

base/urls.py
from django.urls import path

from .views import *

app_name = 'base'

urlpatterns = [

    path('', landing, name = 'landing'),

    path('plans/', plans, name = 'plans'),

    path('contact-us/', contact, name = 'contact'),

    # Info
    path('terms/', terms, name = 'terms'),
    path('privacy/', privacy, name = 'privacy'),
    path('juridical-information/', juridical, name = 'juridical'),
    path('online-payment-safety/', online_payment_safety, name = 'online-payment-safety'),
    path('data-safety/', data_safety, name = 'data-safety'),

]

bloknotik/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('base.urls')),
    path('', include('user.urls')),
    path('', include('app.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from django.conf import settings

from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'user'

urlpatterns = [

    path('login/', log_in, name = 'login'),
    path('register/', register, name = 'register'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name = 'logout'),

]

base/models.py
from django.db import models as m

from django.contrib.auth.models import User

from tinymce.models import HTMLField

class Info(m.Model):

    title = m.CharField(max_length = 300)

    content = HTMLField() 

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        return self.title

    class Meta:

        ordering = ['-title']


class FutureFeature(m.Model):

    title = m.TextField()
    description = m.TextField()

    internal = m.BooleanField(default = False)

    completed = m.BooleanField(default = False)
    completion_date = m.DateField(blank = True)

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        return self.title

    class Meta:

        ordering = ['title']

class UserFeedback(m.Model):

    user = m.OneToOneField(User, on_delete = m.CASCADE, null = True, related_name = 'user_feedback')
    anonymous = m.BooleanField(default = True)

    name = m.TextField(blank = True)

    feedback = m.TextField(blank = True)
    rating = m.PositiveSmallIntegerField(default = 5)

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        if self.user:

            return self.user.username

    class Meta:

        ordering = ['-updated_at']

base/views.py
from django.shortcuts import render

from .models import Info

def landing(request):

    c = {}

    c['logged_in'] = request.user.is_authenticated

    print(c['logged_in'])

    return render(request, 'landing.html', c)

def contact(request):

    return render(request, 'contact.html')

def plans(request):

    return render(request, 'plans.html')

# Info
def terms(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Договор-оферта'), 'id': 'agreement'})

def privacy(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Политика конфиденциальности'), 'id': 'privacy'})

def juridical(request):

    return render(request, 'info/juridical.html')

def online_payment_safety(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Безопасность онлайн платежей'), 'id': 'payment-safety'})
    
def data_safety(request):

    return render(request, 'info/terms.html', {'info': Info.objects.get(title = 'Безопасность данных'), 'id': 'data-safety'})

base/templates/landing.html
{% load static %}
{% load compress %}

<!DOCTYPE html>

<html lang="ru">

    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content = 'width=device-width, initial_scale=1.0' />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        
        
        <title>
            

        </title>

        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link href="" rel="shortcut icon" />

        {% compress css %}

            <link rel="stylesheet" href="{% static 'scss/base/landing.scss' %}" type="text/x-scss">
            <link rel="stylesheet" href="{% static 'scss/base/navs/top-nav.scss' %}" type="text/x-scss">
            <link rel="stylesheet" href="{% static 'scss/base/navs/bottom-nav.scss' %}" type="text/x-scss">

        {% endcompress %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    </head>

    <body>

        <div class="circles">

            <div class="small"></div>
            <div class="medium"></div>
            <div class="big"></div>

        </div>

        <div class="content">

            <div class='top-nav'>

                {% include 'navs/top-nav.html' %}
    
            </div>
    
            <div class='main'>
    
                <div class='text-wrapper'>

                    <div class="text">

                        <h1>

                            Не теряйте голову!
    
                        </h1>
    
                        <h2>
    
                            Создайте онлайн блокнот
    
                        </h2>
        
                        {% if logged_in %}

                            <a href="{% url 'app:home' %}">
                
                                <button>
            
                                    Создать блокнот
                
                                </button>
            
                            </a>

                        {% else %}

                            <a href="{% url 'user:register' %}">
            
                                <button>
            
                                    Создать блокнот
                
                                </button>
            
                            </a>

                        {% endif %}

                    </div>
    
                </div>

                <div class="image">

                    <img src="{% static 'img/base/онлайн_блокнот_заметки.png' %}" alt="Онлайн блокнот с заметками">

                </div>
    
            </div>
    
            <div class="bottom-nav">

                {% include 'navs/bottom-nav.html' %}

            </div>
            
        </div>

    </body>

    <style>

        @font-face {
            
            font-family: Comfortaa;
            src: url("{% static 'fonts/Comfortaa.ttf' %}");
        
        }

        body {

            font-family: Comfortaa;

        }

    </style>

    <script>

        function randomColor(){

            return "#" + ((Math.random() * 16777215) | 0).toString(16);

        }

        function randomNumFromInterval(min, max) {

            return Math.random() * (max - min) + min

        }

        const delay = ms => new Promise(res => setTimeout(res, ms));

        /* Circle animation */

        const animateCircle = async (scale) =>  {

            if (scale == 'big') {

                $('.big').css('background-color', randomColor());

                scale = randomNumFromInterval(1, 1.3);
                $('.big').css('transform', 'scale(' + scale + ')')
                
                await delay(3000);

                $('.big').css('background-color', randomColor());

                scale = randomNumFromInterval(0.7, 1);
                $('.big').css('transform', 'scale(' + scale + ')')


            } else if (scale == 'medium') {

                $('.medium').css('background-color', randomColor());

                scale = randomNumFromInterval(1, 1.6);
                $('.medium').css('transform', 'scale(' + scale + ')')
                
                await delay(1500);

                $('.medium').css('background-color', randomColor());

                scale = randomNumFromInterval(0.6, 1);
                $('.medium').css('transform', 'scale(' + scale + ')')

            } else {

                $('.small').css('background-color', randomColor());

                scale = randomNumFromInterval(1, 1.9);
                $('.small').css('transform', 'scale(' + scale + ')')
                
                await delay(750);

                $('.small').css('background-color', randomColor());

                scale = randomNumFromInterval(0.1, 1);
                $('.small').css('transform', 'scale(' + scale + ')')
                
            }

        }

        

        setInterval(function() {

            animateCircle('big');

        }, 6000)

        setInterval(function() {

            animateCircle('medium');

        }, 3000)

        setInterval(function() {

            animateCircle('small');

        }, 1500)


    </script>

</html>